_commit: fe21eee73f47a659640e02590a3d72ca82f2ca35
_src_path: cookiecutter-monarch-ingest
copyright_year: '2026'
email: kevin@tislab.org
full_name: Kevin Schaper
github_handle: kschaper
github_org: monarch-initiative
license: BSD-3-Clause
project_description: Transform of MAxO Annotations into Biolink Model compliant KGX
project_name: maxo-annotation-ingest
project_slug: maxo_annotation_ingest
